Travis CI: Initial CI build configuration.
AyatanaIndicators/ayatana-indicator-display pull request #15
Opened 2021-06-09 09:58 UTC by sunweaver

2021-08-03 19:33 UTC, tari01 requested changes

2021-08-03 19:33 UTC, tari01 commented on tests/CMakeLists.txt
> +add_test(cppcheck cppcheck --enable=all -USCHEMA_DIR --error-exitcode=2 --inline-suppr --library=qt -I${CMAKE_SOURCE_DIR} -i${CMAKE_SOURCE_DIR}/tests/utils/qmain.cpp ${CMAKE_SOURCE_DIR}/tests --suppr
I had changed this so many times, that I accidentally left out a portion in the end. It should be:

`add_test(cppcheck cppcheck --enable=all -USCHEMA_DIR --error-exitcode=2 --inline-suppr --library=qt -I${CMAKE_SOURCE_DIR} -i${CMAKE_SOURCE_DIR}/tests/utils/qmain.cpp ${CMAKE_SOURCE_DIR}/src ${CMAKE_SOURCE_DIR}/tests --suppress=missingIncludeSystem --suppress=uninitDerivedMemberVar)`

2021-08-04 11:36 UTC, tari01 approved these changes
@sunweaver I see it builds properly. Merge?

2021-08-04 11:43 UTC, sunweaver commented
> @sunweaver I see it builds properly. Merge?

Yes, please. Finally.

2021-08-04 15:03 UTC, tari01 approved these changes

2021-08-04 15:09 UTC, merged